### ISSUE TITLE
Role of "com.societegenerale.commons.plugin.rules.classesForTests" package

### ISSUE THREAD

**Issue by FanJups** [societe-generale/arch-unit-build-plugin-core#19]
## Summary

This package contains two objects related to NoPublicFieldRuleTest that are already present in 
com.societegenerale.aut.test. Should not we delete those duplicated objects ? 

Furthermore what's the role of com.societegenerale.commons.plugin.rules.classesForTests ? It looks like it should contain classes for tests but other packages work fine.

Should we delete this package ?

## Type of Issue

It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

**Comment by vincent-fuchs** [comment]
thanks for pointing it out - I removed the 2 files
