### ISSUE TITLE
Focus on com.societegenerale.aut.test 

### ISSUE THREAD

**Issue by FanJups** [societe-generale/arch-unit-build-plugin-core#21]
## Summary

com.societegenerale.aut.main package also contains classes for tests. Maybe, they should be move to com.societegenerale.aut.test package.

To make the code more readable, I suggest to create sub package in com.societegenerale.aut.test  for each rule we create.

## Type of Issue

It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

**Comment by vincent-fuchs** [comment]
I've added some documentation that got lost at some point : https://github.com/societe-generale/arch-unit-build-plugin-core/commit/7f5e4b032aea79fb39f80feca3bb8069cce6a538 

I don't see the need to create a sub package for each rule. + some of the classes here may be useful for more than one test

**Comment by FanJups** [comment]
Ok, thank you
