### ISSUE TITLE
add a rule to identify String fields that are actually dates 

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/arch-unit-build-plugin-core#24]
## Summary

We regularly see date fields that are not typed properly. however, it's quite easy to identify them by name, because they usually finish by "Date", like 

    String startDate

we need a rule that will look at all the class's String fields : if one of those fields ends by "Date", throw an exception that says : 

    field "startDate" is a String, but it seems to be a Date : if it really is a Date, please change its type accordingly, Strong typing helps write more meaningful code.

**Comment by vincent-fuchs** [comment]
@FanJups , maybe you could implement this rule ?

**Comment by FanJups** [comment]
Sure, this weekend

**Comment by FanJups** [comment]
Sorry, it will be done this week.

**Comment by FanJups** [comment]
@vincent-fuchs , finally done.

**Comment by vincent-fuchs** [comment]
available since v2.5.3 thanks @FanJups !
