### ISSUE TITLE
Use DEBUG log level for debug output

### ISSUE THREAD

**Issue by Bananeweizen** [societe-generale/arch-unit-build-plugin-core#37]
## Summary

The plugin logs everything via INFO level, thereby polluting maven builds with tens of thousands of unwanted lines.

## Type of Issue
 - [X] bug

## Motivation
Be able to read my Maven build output.

## Current Behavior
~~~
[INFO] just built com.my.package.Rules :
[INFO] 1 field rules loaded
[INFO] public static final com.tngtech.archunit.lang.ArchRule com.my.package.Rules.NAME_RULE
[INFO] 0 method rules loaded
[INFO] invoking ConfigurableRule ConfigurableRule(rule=com.my.package.Rules, applyOn=com.societegenerale.commons.plugin.model.ApplyOn@701996e9, checks=[], skip=false) on C:\dev\com.my.bundle.tests\target - /classes/com/my/package
[INFO] Detected Java version 1.8.0_201
[INFO] applying rules on :
[INFO] com.some.package
~~~
And then follows a list of thousands of classes.

## Expected Behavior

Separate log output for end users of your plugin (INFO level) and developers of your plugin (DEBUG level). Especially don't log any lists/collections via INFO level, since that does never scale.

## Steps to Reproduce (for bugs)

Run with custom rule on a large code base.

**Comment by vincent-fuchs** [comment]
this should be fixed in v2.6.1 that just got released. Please re-open if it's not the case.
