### ISSUE TITLE
Failure in resolving classpath when scopePathProvider delivers path with dots

### ISSUE THREAD

**Issue by markusschaefer** [societe-generale/arch-unit-build-plugin-core#44]
## Summary
Wenn resolving the fullPathFromRootTopackage for configurableRules the path is wrong calculated when the ScopePathProvider delivers a path with dots.

## Type of Issue

It is a : 
 - [X] bug
 - [ ] request
 - [ ] question regarding the documentation

## Motivation
When using the Maven Plugin in a Multibranch Pipeline with branch names like minor-1.2 the full classpath is wrong calculated.

## Current Behavior
the path on the filesystem for a branch with name minor-1.2 is calculated to minor-1/2/target/test-classes

## Expected Behavior
the path from the ScopePathProvider should not be replaced. the right path is minor-1.2/target/test-classes

## Steps to Reproduce (for bugs)
see Testcase in PullRequest

## Your Environment

* Version used: 2.7.0
* OS and version: Linux

**Comment by vincent-fuchs** [comment]
thanks a lot @markusschaefer ! I merged, and I will make a 2.7.1 release shortly
