### ISSUE TITLE
ConstantsAndStaticNonFinalFieldsNamesRuleTest usage with serialVersionUID and serialPersistentFields

### ISSUE THREAD

**Issue by tiffmaelite** [societe-generale/arch-unit-build-plugin-core#57]
## Summary

Pre-configured rule ConstantsAndStaticNonFinalFieldsNamesRuleTest cannot be used if the project contains serializable classes having a final static field called serialVersionUID (as per the Serializable class documentation). The only remaining choice seems to either not use this rule, or not care about serializability of the project classes.

Is it possible to have a pre-configured rule which ignores the static final fields which are expected by `java.io.Serializable` (`servialVersionUid` and  `serialPersistentFields`)?

## Type of Issue
It is a : 
 - [ ] bug
 - [X] request
 - [ ] question regarding the documentation

## Motivation
If the project contains a serializable class which follows the recommendation of declaring a static final field called `serialVersionUid` (https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html), and the project *otherwise* wants to enforce the convention of having constants in uppercase, then the build plugin will throw the following exception:
```
[ERROR] java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'fields that are declared in classes that are not enums and are static and are final should be In UpperCase And Use Underscore' was violated (1 times):
[ERROR] Constants have to be written in uppercase. It's possible to add underscore but not at the beginning or the end of the name. - class: com.example.service.MyExampleService - field name: serialVersionUID
```
Since renaming the field would be the same as deleting it and foregoing the goal of defining the serialization version manually, the rule suggestion cannot be followed and the rule must be removed for projects following the Serializable recommendation...
The last option is for all projects using serialization to have the same custom rule. What a shame!

It would be great if arch-unit-build-plugin-core could offer a default pre-configured rule which does not throw assertion errors for Java special fields.

**Comment by vincent-fuchs** [comment]
good catch, thanks for raising this !

I believe I've fixed it, I will try to make a release in coming days/weeks
